### ISSUE TITLE
Light / Dark theme: Switch between themes in sync with the system's dark mode setting

### ISSUE THREAD

**Issue by sam9032** [SchildiChat/schildichat-desktop#110]
Hey there,
it would be amazing, if the client changes the theme as soon as the OS changes its preference.
As far as I can see, the client gets the OS preference only at program start and not if it changes later.

The Electron native interface changes its appearance as soon as the OS changes its preference so maybe there is a way to subscribe to this information from electron?

**Comment by su-ex** [comment]
I assume you are on Linux?!? See the section "Linux system theme detection workaround" here: https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.8.4-sc1

**Comment by sam9032** [comment]
Oh wow.. Yes, I use Linux with the desktop variant.
Thank you so much! The workaround works for schildichat and the Plugin in my OS which switches from day to night even has the option to fire a command as it switches.
The Element Client seems to work different there, the command doesn't work.

I'm following some discussions about the dark mode implementation in various apps and have never heard of the Chromium bug, so thanks for pointing me to this!
Since there are also electron apps that manage the switch without problems, I didn't expect a bug.

So schildichat relies on the CSS prefers-color-scheme media query?

**Comment by su-ex** [comment]
That's a workaround I've added to SchildiChat since this non-adjustment to light/dark got on my nerves, so remember doesn't have it of course. 😁
Light/dark switch was broken with VSCodium (another electron app) some versions ago as well and only recently has this working. I assume they either ship a patched chromium/electron now or they watch some files in the filesystem. Both these options rooms have been to work for me to implement, that's why I have externalized this issue and exposed cli arguments.
Yes, Element and therefore SchildiChat as well listens to changes of prefers-color-scheme. This is fine by Ozarks and works in Firefox but also with electron on Windows and macOS. There was some movement with the chromium issue recently so I hope this will eventually get fixed. In the meantime I'm fine with my workaround.

**Comment by sam9032** [comment]
Thanks for that! :rocket: 
According to the vscode issue https://github.com/microsoft/vscode/issues/102795 electron 13 fixes the problem. Maybe it really has been fixed and will work for all electron apps on Linux, that would be great.

**Comment by su-ex** [comment]
We're already using electron 13, so that's weird. But websites in chromium don't switch light/dark theme as well and the issue is still open in their bugtracker. So I think this will eventually get fixed for electron only once chromium has this fixed.
