### ISSUE TITLE
Add option to switch between Element's and SchildiChat's bubble layout

### ISSUE THREAD

**Issue by adrm** [SchildiChat/schildichat-desktop#113]
Maybe this is not the place for this, please tell me where to post this if it's the case.

Element web has an experimental bubble design with more modern bubble design. Could Schildi implement that instead of its own design? Not because it is a more modern design, but mainly to be more aligned with upstream.

**Comment by su-ex** [comment]
SchildiChat exists because we don't like upstream's design.
Apart from that, the bubble layout from Element is broken (read receipts are way off, member joins and similar are sort of "visually hidden" and misalignment, ...).
It's probably not impossible to add a switch, but I'd probably rather prefer not seeing the bubble layout from Element at all. 🙈
What do you prefer about the bubble layout from Element? More rounded corners?

**Comment by adrm** [comment]
I just discovered this project because I was trying to find a way to have chats and rooms in the same list. Then I saw you also created a new bubble style because it was not available in upstream before. So I thought that maybe now that upstream has an experimental bubble design, you could just use it and save the effort of maintaining your custom design. Also, I like more the more rounded upstream design, but that is secondary.

About what I like more about that design, SchildiChat bubbles remind me to really old Android default chat apps, and I think that the expectation in every chat app now is to have more rounded bubbles, so it was a bit surprising for me when I started using SchildiChat.

**Comment by su-ex** [comment]
The bubbles are exactly like we, the developers of SchildiChat, like them. We find all this rounded stuff horrible. So for us they don't look outdated, but wonderful. 🤩😆
This is probably a matter of taste since many people seem to prefer rounded bubbles.
It's long planned to have the option to set custom border radii so this is configurable, but I just didn't have time to implement this yet.

**Comment by su-ex** [comment]
SchildiChat now has the option to change corner radii.
