### ISSUE TITLE
German Mode

### ISSUE THREAD

**Issue by eest9** [SchildiChat/schildichat-desktop#139]
I find the Markdown syntax highly annoying. Every time I write German texts, I have to read them multiple times in order to find every asterisk used in my text in order to mask them. And sometimes (I couldn't figure out why) the mask doesn't work. So most of the time I'll end up putting `/plain` in front of my texts whether I want to use Markdown or not, just because I wouldn't be able to send German texts otherwise. (In German Asterisk are used to construct a gender neutral genus e.g. "Arbeiter" would be a male worker, "Arbeiterin" a female worker and "Arbeiter*in" would be a worker without a specified gender)

Since I often want to use other markdown Features like code highlighting regardless of the language the message is written in, I would like to see a feature where I could deactivate or assign another character for the italic highlighting.

**Comment by Kloenk** [comment]
The formatted part in the matrix spec is html, so for that it's just the work to convince the markdown parser. But what about the non formatted body. Should the chat then sends stars there, so that clients which do not read the formatted body can show valid markdown?

So It's rather a spec thing then just a client IMHO

**Comment by SpiritCroc** [comment]
It's your decision to use gender stars or not in the German language, just saying.

I agree that Markdown is not the best for sending formatted messages in a messenger. However, rather than messing with the Markdown syntax, it makes more sense to me to get some kind of SYSIWYG editor, similar to what telegram has. Unless there's some easy to implement library for that, it's likely out of scope for SchildiChat though.

**Comment by SpiritCroc** [comment]
I don't think it's a spec thing though, unless the spec tells clients to interpret the fallback body as markdown, which would be weird, I think it should be just plain text (so removing all formatting should be fine) :thinking:

**Comment by Kloenk** [comment]
> I don't think it's a spec thing though, unless the spec tells clients to interpret the fallback body as markdown, which would be weird, I think it should be just plain text (so removing all formatting should be fine) 🤔

Yes, it does not tell you to send in markdown, but also don't tells to don't send markdown. IIRC I saw both, some send the markdown text there. Not entirely sure what SC does currently.

**Comment by SpiritCroc** [comment]
> > I don't think it's a spec thing though, unless the spec tells clients to interpret the fallback body as markdown, which would be weird, I think it should be just plain text (so removing all formatting should be fine) thinking
> 
> Yes, it does not tell you to send in markdown, but also don't tells to don't send markdown. IIRC I saw both, some send the markdown text there. Not entirely sure what SC does currently.

Doesn't matter what clients send, as long as none assumes it can parse the fallback as markdown

**Comment by su-ex** [comment]
Upstream is now working on a wysiwyg-Editor, it's already inside labs.
