### ISSUE TITLE
Visually seperate images from the background

### ISSUE THREAD

**Issue by ShadowJonathan** [SchildiChat/schildichat-desktop#39]
Just like discord, have a different gradient (i.e. lighter with dark mode, darker with light mode) behind image bubbles to distinguish them against the background, it also makes it easier to recognise "images" in chat history even if they're still loading.

**Comment by su-ex** [comment]
No, transparent images should be transparent, especially stickers for example.

**Comment by su-ex** [comment]
@ShadowJonathan , @<span>whoever has an idea</span>
I agree this would be beneficial in _some_ cases.

Stickers should stay without, but instead of a background a border might be an option, because a background can change the intended image appearance while a border doesn't and also wouldn't work for images with the theme's background.

It would appear like that then:
![Bildschirmfoto von 2021-01-30 11-55-14](https://user-images.githubusercontent.com/9221456/106355165-979c1e80-62f6-11eb-8b52-463019a9e1be.png)

**Comment by su-ex** [comment]
Would you prefer an image as bubble approach which WhatsApp has or the Telegram approach with a small border?
