### ISSUE TITLE
[BUG] On OSX (MacOS) did not show application icon

### ISSUE THREAD

**Issue by savegame** [SchildiChat/schildichat-desktop#68]
<img width="104" alt="Снимок экрана 2021-05-03 в 16 54 14" src="https://user-images.githubusercontent.com/16311332/116885123-330f9900-ac30-11eb-9804-2c488b11c6e0.png">

In middle position - SchildiChat

**Comment by su-ex** [comment]
@michi7801
Some ideas?

**Comment by michi7801** [comment]
First of all, try to restart your computer. MacOS sometimes has problems to obtain the app icon shortly after installing the app. This does not happen to often, but it is worth the try.

### If this does not help: 
Did you build the app yourself or did you use the prebuild dmg? Placing the app icon into the right place is the job of the `electron-builder`. It should work fine as long as the image is at the right place. 

If you are using the prebuild, try to install it again. The icon is definitely existing in the prebuild. Maybe the process of copying the `.app` went wrong?
If not, check if the app image is in the right place and rebuild the app yourself.


I am not aware that the current version of the MacOS installer has any flaws, but I look into it if the problems occurs again...

**Comment by savegame** [comment]
1. App get from Releases. 
2. App icon not shown when i open just DMG   
3. I allready reboot OSX, its not help.  
<img width="652" alt="Снимок экрана 2021-05-03 в 18 52 28" src="https://user-images.githubusercontent.com/16311332/116899831-b933db80-ac40-11eb-9a21-69a8ab990bf6.png">

**Comment by michi7801** [comment]
Ok, I just re-downloaded the current release myself and checked if the icon is present. You can try to also re-download it, otherwise I have no clue why this could be. I also checked the image with a VM, which is not registered with my AppleID, and it works just fine. You can try to look if the app icon is present in the `.app` file.

Just go to this path:
`/Applications/SchildiChat.app/Contents/Resources`
and look if the file named `SchildiChat.icns` is present.

If this is the case, it has nothing to do with the SchildiChat installation. Something else must be going on with your machine....
It this is not the case, your installation is faulty or the dmg file is faulty...

**Comment by savegame** [comment]
strange, icon in app file is present. 
dont know why it not show ...

**Comment by austinhuang0131** [comment]
Reproducible on Mojave.

Currently using [this](https://appleinsider.com/articles/21/01/06/how-to-change-app-icons-on-macos) as a remedy.

**Comment by su-ex** [comment]
@Kloenk Do you think this might be fixed with your recent changes?

**Comment by Kloenk** [comment]
Im not sure, could be. Don't have easy access to an pre 11 macOS right now.

**Comment by su-ex** [comment]
Did the latest version fix this? @austinhuang0131 @savegame

**Comment by austinhuang0131** [comment]
@su-ex Yes but the icon looks kinda small (compared to others)

![Screen Shot 2021-09-14 at 09 29 33](https://user-images.githubusercontent.com/16656689/133266439-0d678c31-371e-4408-b72b-bf34b565962d.png)

**Comment by Kloenk** [comment]
I build the icon with the guidelines of apple, so this is the size that is expected.
See: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by Kloenk** [comment]
Will close this. If it reappears just reopen it.
