### ISSUE TITLE
Theming: Username Colors don't change in Bubble layout.

### ISSUE THREAD

**Issue by entrapta-dev** [SchildiChat/schildichat-desktop#79]
Theming is shaping up nicely as seen in #34.  
My current issue I have discovered is with username-colors.

**Situation:**  
Set `"username-colors": ["#aaaaaa", #bbbbbb", etc],` in my custom theme.

**Expected result:**  
Different username colors based on the ones set in the theme.

**Actual result:**  
All usernames use the set `accent-color` from the theme instead. Which is a fixed, single color.

This _only_ happens when in Settings, Appearance is set to use the Message bubbles layout. It works fine without the bubbles in the other two layouts; Modern and IRC; and I see the usernames with the specific list of colors I have set in my theme.

This appears to be due to the fact that in .`sc_BubbleLayout .mx_SenderProfile_displayName` the `color` is set to `var(--accent-color)!important`.  
Disabling this tag via the the Inspect console (Ctrl+Shift+I) fixes the issue entirely and I see all the custom colors I set in the theme. However, I have no idea how to override that in the theme, or if that can currently be done at all.

SchildiChat version: 1.7.32-sc1

**Comment by su-ex** [comment]
This is currently by intention because with the bubble layout the username wanders into the bubble and therefore there's no need for seperator by color.
However, it is planned to implement something similar to Android which let's you choose if username colors should be uniform (currently with the bubble layout), based on power level or based on mxid (currently with the other layouts) seperately for each DMs, groups and public rooms.

**Comment by entrapta-dev** [comment]
Ah, I was wondering if I missed something because I do have it set to use mxid for username colors on Android. I'll wait for the desktop implementation of that then and continue on the other parts of the theme that are currently supported. Thanks!
